version: "3"

services:
  db-postgres-evento:
    image: postgres:alpine
    ports:
      - "5432:5432"
    container_name: db-postgres-evento
    restart: always
    volumes:
      - ./banco-de-dados-evento:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: pg
      POSTGRES_PASSWORD: pg

volumes:
  banco-de-dados-evento:
